# Generated by Django 3.2.3 on 2021-06-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pw_wowProj', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='birth',
            new_name='dataNascimento',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='telemovel',
        ),
    ]
