# Generated by Django 3.2.3 on 2021-06-09 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pw_wowProj', '0002_auto_20210608_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=32)),
                ('level', models.IntegerField(choices=[(60, 'Vanilla'), (70, 'Burning Crusade')], default=60)),
            ],
        ),
        migrations.CreateModel(
            name='raiddifficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dificuldade', models.CharField(max_length=6)),
                ('codigo', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='contacto',
            name='apelido',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nome',
            field=models.CharField(max_length=32),
        ),
        migrations.CreateModel(
            name='Raider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=24)),
                ('role', models.IntegerField(choices=[(0, 'DPS'), (1, 'Healer'), (2, 'Tank')], default=0)),
                ('charclass', models.IntegerField(choices=[(1, 'hunter'), (2, 'shamman'), (3, 'rogue'), (4, 'druid'), (5, 'warrior'), (6, 'paladin'), (7, 'warlock'), (8, 'priest'), (9, 'mage')], default=1)),
                ('raids', models.ManyToManyField(blank=True, related_name='Raiders', to='pw_wowProj.Raid')),
            ],
        ),
        migrations.AddField(
            model_name='raid',
            name='difficulty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diff', to='pw_wowProj.raiddifficulty'),
        ),
    ]
