# Generated by Django 3.2.3 on 2021-06-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pw_wowProj', '0003_auto_20210609_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raider',
            name='charclass',
            field=models.CharField(choices=[('Hunter', 'hunter'), ('Shamman', 'shamman'), ('Rogue', 'rogue'), ('Druid', 'druid'), ('Warrior', 'warrior'), ('Paladin', 'paladin'), ('Warlock', 'warlock'), ('Priest', 'priest'), ('Mage', 'mage')], default='Hunter', max_length=7),
        ),
        migrations.AlterField(
            model_name='raider',
            name='role',
            field=models.CharField(choices=[('Damage Dealer', 'dps'), ('Healer', 'healer'), ('Tank', 'tank')], default='Damage Dealer', max_length=13),
        ),
    ]
