# Generated by Django 3.2.3 on 2021-06-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pw_wowProj', '0004_auto_20210609_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='telemovel',
            field=models.CharField(default='xd', max_length=13),
        ),
    ]
