# Generated by Django 3.2.3 on 2021-07-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pw_wowProj', '0005_contacto_telemovel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbackName', models.CharField(max_length=32)),
                ('feedbackEmail', models.EmailField(max_length=254)),
                ('feedbackSubject', models.TextField()),
            ],
        ),
    ]
